language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 
  - 2.2
  - 2.1

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1

install:
  - dotnet restore src/AspnetCoreDoc.sln

script:
  - dotnet build src/AspnetCoreDoc.sln
  - dotnet test src/AspnetCoreDoc.sln
