language: csharp
mono: none
dist: trusty
dotnet: 
  - 2.0.9
  - 2.1.10
  - 2.2.4

install:
  - dotnet restore src/AspnetCoreDoc.sln

script:
  - dotnet build src/AspnetCoreDoc.sln
  - dotnet test src/AspnetCoreDoc.sln
