language: csharp
mono: none
dist: trusty

branches:
  only:
    - master
    - vue-ui
    
dotnet: 
  - 2.2.100
  - 2.1.603

install:
  - dotnet restore src/AspnetCoreDoc.sln

script:
  - dotnet build src/AspnetCoreDoc.sln
  - dotnet test src/AspnetCoreDoc.sln
